### ISSUE TITLE
同學你好，請問你這學期也有修吳尚鴻的DL嗎

### ISSUE THREAD

**Issue by Chancing0** [ginagigo123/NTHU-Deep-Learning-Course#1]
我也是旁聽了一學期，老師最後一堂課的總結講的很好，我看到TA有錄下來，不知道TA有沒有開放給修課同學下載，如果有，我想跟你求一份，用於溫習吸收。我會給您感謝費用100。
這是我的FB：
https://www.facebook.com/profile.php?id=100005220045328

**Comment by ginagigo123** [comment]
> 我也是旁聽了一學期，老師最後一堂課的總結講的很好，我看到TA有錄下來，不知道TA有沒有開放給修課同學下載，如果有，我想跟你求一份，用於溫習吸收。我會給您感謝費用100。 這是我的FB： https://www.facebook.com/profile.php?id=100005220045328

同學你好，我有修這學期的DL課程，然後如果我之後有拿到影片的話，再透過FB傳給你，感謝你～

**Comment by Chancing0** [comment]
我有請問過TA，他們說只能修課同學才能要該堂課的錄像。我是旁聽所以無法，可以麻煩你以修課生的身份跟TA要錄像嗎。我願意給你500元的酬勞費用。然後請説是你自己想要的，不要説出是給課外同學的，那樣TA可能就還是不會給。
老師最後一堂課太棒了，我非常非常想溫習，感謝！！
